#!/bin/bash
# Author: Pablo Iranzo Gómez (Pablo.Iranzo@gmail.com)  https://iranzo.github.io
# Description: Change password of PDF file

mkdir -p noenc enc
FILE="$1"
PASS="$2"
qpdf --encrypt "$PASS" "$PASS" 128 -- "$FILE" "enc/$FILE"
[ "$?" == "0" ] && mv "$FILE" "noenc/$FILE"
